### PR TITLE
Don't show sorting arrows on columns without header

### PR DESCRIPTION
**Pull request by Bluesmile82**
- Don't show sorting arrows on columns without header: To try add the link column to the table:
- Fix the total width of the chart calculation based in the columns width

image

### CODE REVIEW

**Comment by Bluesmile82** [comment]
You are right! This might be a problem with the table width. I will take a look a it

**Comment by aabdaab** [comment]
Thank you 🙇‍♀️

**Comment by Bluesmile82** [comment]
Yeah, just fixed that. I'm happy that we did this change. Will fix some length problems in the tables

**Comment by aabdaab** [comment]
working perfectly now, thanks! 🥇

**Pull request merged**
